apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    cert-manager.io/disable-validation: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: ingress