apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    helmVersion: {{ $.Chart.Version }}
    helmAppVersion: {{ $.Chart.AppVersion }}
    helmName: {{ $.Chart.Name }}
spec:
  type: ClusterIP
  ports:
    {{- toYaml .Values.service.portMappings | nindent 2 }}
  selector:
    app: {{ .Values.name }}
