apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  # service: "map[beta:map[kubernetes:map[io/azure-load-balancer-resource-group:{{ .Values.nginx.loadBalancer.azResourceGroup }}]]]"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  loadBalancerIP: {{ .Values.nginx.loadBalancer.publicIp }}
  selector:
    app: nginx-ingress
